function color = tissue_colour(tissue_name)
    tissue_map = containers.Map( ...
        {'White Matter', 'Grey Matter', 'Cerebro Spinal Fluid', ...
         'Dura', 'Cancellous Bone', 'Cortical Bone', 'Fat', 'Skin'}, ...
        { '#EAEAEA', ... 
          '#A29E9B', ... 
          '#6CA6C1', ...
          '#556B2F', ... 
          '#9B1C3D', ... 
          '#F5F5DC', ... 
          '#F1E5A9', ... 
          '#A86F4F' ... 
        });

    disp(['Looking up color for: ', tissue_name]);

    if isKey(tissue_map, tissue_name)
        color = tissue_map(tissue_name); % Return corresponding color
    else
        error('Tissue name not found');
    end
end

